[package]
name = "amplicontig"
version = "0.2.0"
authors = ["jeff-k <jeff_k@fastmail.com>"]
edition = "2021"

[dependencies]
bio = "*"
clap = "*"
flate2 = "*"
csv = "*"
serde = "*"
trie = "*"
fst = { version = "*", features = ["levenshtein"] }
