[package]
name = "amplicontig"
version = "0.1.2"
authors = ["jeff-k <jeff_k@fastmail.com>"]
edition = "2018"

[dependencies]
bio = "*"
clap = "*"
flate2 = "*"
csv = "*"
serde = "*"
trie = "*"
levenshtein_automata = "*"
