[package]
name = "amplicontig"
version = "0.3.0"
authors = ["jeff-k <jeff_k@fastmail.com>"]
edition = "2021"

[dependencies]
bio = "*"
clap = { version = "^3.1", features = ["cargo"] }
flate2 = "*"
csv = "^1.1"
serde = "*"
